---
# File: setup.yml
# Part: Nginx
#
# Description: Install and configure an Nginx server
#
# Parameters:
# - nginx_flavour

# Dependencies ([part:]type:filename):
# - vars:main.yml
# - handlers:handlers.yml
#
# OS familly: Ubuntu (>= 12.04)

- name: Nginx | Add Nginx apt repository
  apt_repository: repo=ppa:nginx/stable

- name: Nginx | Install Nginx ('$nginx_flavour' version)
  apt:
    pkg=nginx-$nginx_flavour
    update_cache=yes
    force=yes

- name: Nginx | Push main config file
  template:
    src=$repository_basedir/nginx/templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root group=root mode=0644

- name: Nginx | Disable default server block
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Nginx | Insure Nginx is running
  service:
    name=nginx
    state=started

