---
# File: setup.yml
#
# Description: Install and configure Mercurial
#
# Parameters:
#
# Dependencies ([part:]type:filename):
#
# OS familly: Debian


- name: Hg | Install Mercurial base packages
  apt: pkg=$item state=installed
  with_items:
        - mercurial

# Install the default templates
- name: Hg | Push global hgrc template
  template:
    src=$repository_basedir/hg/templates/hgrc.j2
    dest=/etc/mercurial/hgrc

