---
- hosts: hosts
  user: vagrant
  sudo: True

  vars:
    repository_basedir: ../../ansible-repository

  tasks:
    - include: $repository_basedir/nginx/tasks/setup.yml
    - include: $repository_basedir/nginx/tasks/vhost_add.yml create_root=true name=test.webdev.vt root=/vagrant/www 

  handlers:
    - include: $repository_basedir/nginx/handlers/handlers.yml
