---

- hosts: webservers
  user: vagrant 
  sudo: True

  vars:
    repository_basedir: ..
    hg_username: "Some User <somemail@somedomain.com>"
  # Optionnaly we can define authentification groups, 
  # so that Hg doesn't not ask for IDs on every push, pull, etc.
    hg_authgroups:
    - grp: 'default'
      prefix: 'domain'
      username: 'some.user'
      password: 'MichaelIsNotDead'
      schemes: 'http'

  tasks:
  - include: $repository_basedir/hg/tasks/setup.yml
